apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ollive

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres/deployment.yaml
  - postgres/service.yaml
  - redis/deployment.yaml
  - redis/service.yaml
  - backend/deployment.yaml
  - backend/service.yaml
  - backend/hpa.yaml
  - worker/deployment.yaml
  - worker/hpa.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - ingress.yaml
